import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header style={{ padding: 12, borderBottom: "1px solid #eee", display: "flex", gap: 12 }}>
          <a href="/">Home</a>
          <a href="/buyers">Buyers</a>
          <a href="/buyers/new">New</a>
          <span style={{ marginLeft: "auto" }} />
          <form action="/api/auth/signout" method="post">
            <button type="submit" style={{ border: "1px solid #ddd", padding: 6 }}>Logout</button>
          </form>
        </header>
        <main style={{ padding: 16 }}>{children}</main>
      </body>
    </html>
  );
}
